// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.22.0--rc3
// source: pkg/sudoku/sudoku.proto

package sudoku

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Question struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board      []int32 `protobuf:"varint,1,rep,packed,name=board,proto3" json:"board,omitempty"`
	SolverType string  `protobuf:"bytes,2,opt,name=solverType,proto3" json:"solverType,omitempty"`
}

func (x *Question) Reset() {
	*x = Question{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_sudoku_sudoku_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sudoku_sudoku_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_pkg_sudoku_sudoku_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetBoard() []int32 {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *Question) GetSolverType() string {
	if x != nil {
		return x.SolverType
	}
	return ""
}

type Solution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Solved   bool    `protobuf:"varint,1,opt,name=solved,proto3" json:"solved,omitempty"`
	Board    []int32 `protobuf:"varint,2,rep,packed,name=board,proto3" json:"board,omitempty"`
	Duration float64 `protobuf:"fixed64,3,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *Solution) Reset() {
	*x = Solution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_sudoku_sudoku_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Solution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solution) ProtoMessage() {}

func (x *Solution) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sudoku_sudoku_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solution.ProtoReflect.Descriptor instead.
func (*Solution) Descriptor() ([]byte, []int) {
	return file_pkg_sudoku_sudoku_proto_rawDescGZIP(), []int{1}
}

func (x *Solution) GetSolved() bool {
	if x != nil {
		return x.Solved
	}
	return false
}

func (x *Solution) GetBoard() []int32 {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *Solution) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_pkg_sudoku_sudoku_proto protoreflect.FileDescriptor

var file_pkg_sudoku_sudoku_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x75, 0x64, 0x6f, 0x6b, 0x75, 0x2f, 0x73, 0x75, 0x64,
	0x6f, 0x6b, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x75, 0x64, 0x6f, 0x6b,
	0x75, 0x22, 0x40, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x54, 0x0a, 0x08, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x3d, 0x0a, 0x06, 0x53, 0x75, 0x64,
	0x6f, 0x6b, 0x75, 0x12, 0x33, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6c, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x6b, 0x75, 0x2e, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x10, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x6b, 0x75, 0x2e, 0x53, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x73, 0x75, 0x64, 0x6f,
	0x6b, 0x75, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73,
	0x75, 0x64, 0x6f, 0x6b, 0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_sudoku_sudoku_proto_rawDescOnce sync.Once
	file_pkg_sudoku_sudoku_proto_rawDescData = file_pkg_sudoku_sudoku_proto_rawDesc
)

func file_pkg_sudoku_sudoku_proto_rawDescGZIP() []byte {
	file_pkg_sudoku_sudoku_proto_rawDescOnce.Do(func() {
		file_pkg_sudoku_sudoku_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_sudoku_sudoku_proto_rawDescData)
	})
	return file_pkg_sudoku_sudoku_proto_rawDescData
}

var file_pkg_sudoku_sudoku_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_sudoku_sudoku_proto_goTypes = []interface{}{
	(*Question)(nil), // 0: sudoku.Question
	(*Solution)(nil), // 1: sudoku.Solution
}
var file_pkg_sudoku_sudoku_proto_depIdxs = []int32{
	0, // 0: sudoku.Sudoku.GetSolution:input_type -> sudoku.Question
	1, // 1: sudoku.Sudoku.GetSolution:output_type -> sudoku.Solution
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_sudoku_sudoku_proto_init() }
func file_pkg_sudoku_sudoku_proto_init() {
	if File_pkg_sudoku_sudoku_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_sudoku_sudoku_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Question); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_sudoku_sudoku_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Solution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_sudoku_sudoku_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_sudoku_sudoku_proto_goTypes,
		DependencyIndexes: file_pkg_sudoku_sudoku_proto_depIdxs,
		MessageInfos:      file_pkg_sudoku_sudoku_proto_msgTypes,
	}.Build()
	File_pkg_sudoku_sudoku_proto = out.File
	file_pkg_sudoku_sudoku_proto_rawDesc = nil
	file_pkg_sudoku_sudoku_proto_goTypes = nil
	file_pkg_sudoku_sudoku_proto_depIdxs = nil
}
