# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sudoku.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csudoku.proto\x12\x06sudoku\"-\n\x08Question\x12\r\n\x05\x62oard\x18\x01 \x03(\x05\x12\x12\n\nsolverType\x18\x02 \x01(\t\";\n\x08Solution\x12\x0e\n\x06solved\x18\x01 \x01(\x08\x12\r\n\x05\x62oard\x18\x02 \x03(\x05\x12\x10\n\x08\x64uration\x18\x03 \x01(\x01\x32=\n\x06Sudoku\x12\x33\n\x0bGetSolution\x12\x10.sudoku.Question\x1a\x10.sudoku.Solution\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sudoku_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUESTION']._serialized_start=24
  _globals['_QUESTION']._serialized_end=69
  _globals['_SOLUTION']._serialized_start=71
  _globals['_SOLUTION']._serialized_end=130
  _globals['_SUDOKU']._serialized_start=132
  _globals['_SUDOKU']._serialized_end=193
# @@protoc_insertion_point(module_scope)
